name: Build and Release

on:
  push:
    branches:
      - main
      - development
      - rc-v*
      - release/*
      - hotfix/*
    pull_request:
      types: [ready_for_review, opened, reopened, auto_merge_enabled]

jobs:
  build:
    strategy:
      matrix:
        include:
          - targetPlatform: linux
            os: ubuntu-latest
          - targetPlatform: macos
            os: ubuntu-latest
          - targetPlatform: windows
            os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install
        shell: bash
        run: yarn install --immutable
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Setup OS variables
        run: bash scripts/configure-artifact.sh ${{ matrix.targetPlatform }}

      - name: Copy config.json from the last release
        shell: bash
        run: |
          mkdir pack-dist
          set -ex
          mkdir -p dist
          curl -o "dist/config.json" 'https://release.nine-chronicles.com/9c-launcher-config.json'

      - name: build
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == "main" ]]
          then
            yarn release:${{ matrix.targetPlatform }}
          else
            yarn run pack:${{ matrix.targetPlatform }}
          fi

      - name: zip
        shell: bash
        run: |
          cd pack/Nine\ Chronicles-$OS_ALIAS-x64/
          $ZIP_CMD ../../pack-dist/$ARTIFACT *

      - uses: actions/upload-artifact@v3
        with:
          path: pack-dist
          name: Build-${{ matrix.targetPlatform }}
          retention-days: 7
          if-no-files-found: error

      - name: upload
        shell: bash
        run: |
          aws s3 cp "pack-dist/$ARTIFACT" "s3://9c-artifacts/9c-launcher/${{ github.sha }}/$ARTIFACT"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

  styles:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install
        shell: bash
        run: yarn

      - name: Check Formatting
        run: yarn prettier --check "src/**/*.{ts,tsx,json}"

      - run: yarn codegen

      - name: Type Check
        run: yarn tsc --noEmit

      - name: ESLint Check
        run: yarn eslint ./src --quiet

  update-translations:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install
        shell: bash
        run: yarn

      - name: Update Translations
        run: yarn update-translations
        env:
          TRANSIFEX_SECRET: ${{ secrets.TRANSIFEX_SECRET }}
          TRANSIFEX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
